FROM node:slim

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json jsconfig.json /usr/src/app/

RUN npm install

ADD src /usr/src/app/src

CMD [ "npm", "start" ]
