# base image
FROM node:9

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json webpack.common.js webpack.dev.js /usr/src/app/
RUN npm install

# start app
CMD ["npm", "start"]